version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pollsapi/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r pollsapi/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "pollsapi/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd pollsapi
            python manage.py test
      - run:
          name: Create test-reports folder if not exists
          command: mkdir -p test-reports


      - store_artifacts:
          path: test-reports
          destination: test-reports
